### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by dmcclean** [bjornbm/numtype-dk#10]
Is `NumType` a good name for the main type of this package? Maybe it should be `TypeInt` or similar?

Package name seems fine, especially if we later want to tackle type rationals.

**Comment by bjornbm** [comment]
I don't feel strongly about it and wouldn't object to a more appropriate name for the type. `TypeInt` would be fine for me.

**Comment by dmcclean** [comment]
OK, even though it is bikeshedding and a lot of churn I am going to bite the bullet, because I want to tackle type rationals in the future and this module would seem like a sensible home for both.

Hold off on hackage for a bit.

**Comment by dmcclean** [comment]
All set, modulo possible minor 7.8 issues.
