### ISSUE TITLE
Explicit export list?

### ISSUE THREAD

**Issue by dmcclean** [bjornbm/numtype-dk#8]
Right now the 'Numeric.NumType.DK' module has an implicit export list. As a result, it appears to implicitly re-export all the stuff it imports from 'Data.Proxy'.

This wouldn't necessarily be a problem, except that it leads to warnings if something like 'Numeric.Units.Dimensional.DK' imports 'Numeric.NumType.DK' and also explicitly imports 'Data.Proxy', because the latter import is redundant. It's redundant in a subtle way, which makes the warning quite confusing.

I'd suggest switching to an explicit export list that doesn't re-export the proxy machinery, but I'm not sure if there are other clients that would be broken by the change.

**Comment by dmcclean** [comment]
But wait, this isn't how the haskell report says implicit export lists work, so now I am actually even more confused.

**Comment by bjornbm** [comment]
I'm not worried about other clients. We haven't even put this on Hackage yet! We'll just bump the version number appropriately. Would be happy to take a pull request! :)




Disclaimer: I'm not sure if I omitted explicit exports out of laziness (or intent to do it later) or if there was a problem/ambiguity about how to export (or not export) implicit kinds when they were all new and hot.

**Comment by dmcclean** [comment]
Explicit lists might be good just for documentation, but I'm more interested now in figuring out what actually causes the warning that the import in Numeric.Units.Dimensional.DK of Data.Proxy is redundant, when Proxy is used all over the place and doesn't appear to be imported anywhere else.

**Comment by dmcclean** [comment]
It comes for free when you import Data.Typeable, confusingly.

**Comment by dmcclean** [comment]
Fixed by #9.
